MODEL_PROFILES = [
    {
        "id": "eco",
        "name": "低配 / CPU",
        "description": "规则 + 可训练字符 n-gram 模型，内存占用低、无需下载权重。",
        "recommended_ram_gb": 4,
        "gpu_required": False,
        "classifier_provider": "builtin_nb",
        "classifier_model": "builtin/char-ngram-nb",
    },
    {
        "id": "balanced",
        "name": "均衡 / 8–16 GB 内存",
        "description": "规则与本地分类器先筛选，疑似消息交给 Qwen3Guard 0.6B 复核。",
        "recommended_ram_gb": 8,
        "gpu_required": False,
        "classifier_provider": "transformers",
        "classifier_model": "Qwen/Qwen3Guard-Gen-0.6B",
    },
    {
        "id": "quality",
        "name": "高质量 / 独显",
        "description": "使用 Qwen3Guard 4B 复核；建议 NVIDIA 8 GB 以上显存或较大系统内存。",
        "recommended_ram_gb": 16,
        "gpu_required": True,
        "classifier_provider": "transformers",
        "classifier_model": "Qwen/Qwen3Guard-4B-Gen",
    },
]


MODEL_CATALOG = {
    "profiles": MODEL_PROFILES,
    "embedding": [
        {
            "provider": "hashing",
            "model": "builtin/char-ngram-zh-v1",
            "name": "内置字符语义模型",
            "description": "零下载、CPU 即用，用于规则样例的近似召回。",
            "local": True,
            "installed": True,
        },
        {
            "provider": "sentence_transformers",
            "model": "BAAI/bge-small-zh-v1.5",
            "name": "BGE Small 中文",
            "description": "可选的轻量中文向量模型，首次启用时下载。",
            "local": True,
            "installed": False,
        },
        {
            "provider": "sentence_transformers",
            "model": "BAAI/bge-m3",
            "name": "BGE-M3",
            "description": "兼顾中文、多语言和较长文本的语义召回模型，首次启用时下载。",
            "local": True,
            "installed": False,
        },
        {
            "provider": "sentence_transformers",
            "model": "Qwen/Qwen3-Embedding-0.6B",
            "name": "Qwen3 Embedding 0.6B",
            "description": "中文语义泛化能力更强，资源占用高于 BGE Small，首次启用时下载。",
            "local": True,
            "installed": False,
        },
        {
            "provider": "openai_compatible",
            "model": "text-embedding-3-small",
            "name": "OpenAI 兼容 Embedding",
            "description": "连接任意兼容 /v1/embeddings 的本地服务或模型网关。",
            "local": False,
            "installed": False,
        },
    ],
    "classifier": [
        {
            "provider": "builtin_nb",
            "model": "builtin/char-ngram-nb",
            "name": "字符 n-gram 分类器",
            "description": "系统内置训练与推理，无第三方机器学习依赖；适合低配 CPU。",
            "local": True,
            "installed": True,
            "trainable": True,
        },
        {
            "provider": "heuristic",
            "model": "builtin/heuristic-zh-v1",
            "name": "仅规则判定器",
            "description": "不加载模型，只使用关键词、正则和例外规则。",
            "local": True,
            "installed": True,
            "trainable": False,
        },
        {
            "provider": "transformers",
            "model": "Qwen/Qwen3Guard-Gen-0.6B",
            "name": "Qwen3Guard 0.6B",
            "description": "中文通用安全复核；需安装 PyTorch/Transformers 并下载权重。",
            "local": True,
            "installed": False,
            "trainable": False,
        },
        {
            "provider": "transformers",
            "model": "Qwen/Qwen3Guard-4B-Gen",
            "name": "Qwen3Guard 4B",
            "description": "更高质量的本地复核器，建议 8 GB 以上显存。",
            "local": True,
            "installed": False,
            "trainable": False,
        },
        {
            "provider": "openai_compatible",
            "model": "qwen3guard:0.6b",
            "name": "本机 Ollama / vLLM / LM Studio",
            "description": "连接用户已经启动的本机 OpenAI 兼容服务，不使用云 API。",
            "local": True,
            "installed": False,
            "trainable": False,
        },
    ],
    "vision": [
        {
            "kind": "qrcode",
            "provider": "zxingcpp",
            "model": "ZXing-C++",
            "name": "ZXing 二维码检测",
            "description": "只返回图片是否包含二维码及数量，不读取或审核二维码内容。",
            "local": True,
            "installed": True,
        },
        {
            "kind": "ocr",
            "provider": "rapidocr",
            "model": "RapidOCR ONNX",
            "name": "RapidOCR 中文 OCR",
            "description": "CPU 本地提取海报文字，结果自动进入文本审核流水线。",
            "local": True,
            "installed": False,
        },
        {
            "kind": "nsfw",
            "provider": "nudenet",
            "model": "NudeNet ONNX",
            "name": "NudeNet",
            "description": "轻量 ONNX 人体敏感区域检测，适合 CPU；可配置命中阈值。",
            "local": True,
            "installed": False,
        },
        {
            "kind": "nsfw",
            "provider": "opennsfw2",
            "model": "OpenNSFW2",
            "name": "OpenNSFW2",
            "description": "整图色情概率分类器，需要额外 Keras 后端。",
            "local": True,
            "installed": False,
        },
    ],
}
